spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSLDialect

  mail:
    host: localhost
    ports:
      1025
    username: alv
    password: alv
    properties:
      mail:
        smtp:
          trust: "*"
        auth:
          true
        starttls:
          enable: true
        connectiontimeout:
          5000
        timeout:
          3000
        writetimeout:
          5000

